name: Build & test

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - master

jobs:
  exec:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        c_compiler: [gcc, clang, cl]
        build_type: [Debug, Release]
        include:
          - c_compiler: gcc
            cxx_compiler: g++
          - c_compiler: clang
            cxx_compiler: clang++
          - c_compiler: cl
            cxx_compiler: cl
          - os: windows-latest
            test_name: .\Bin\UnitTest.exe
          - os: ubuntu-latest
            test_name: ./Bin/UnitTest
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    name: Build & test (${{ matrix.cxx_compiler }} / ${{ matrix.build_type }} / ${{ matrix.os }})
        
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Install conan
      shell: bash
      run: |
        pip install conan

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./Bin/UnitTest
